[package]
name = "leetcode"
version = "0.1.0"
authors = ["Zane Hitchcox <zwhitchcox@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
